# fly.toml file generated for stupidjoey-gpt-reader on 2023-04-16T18:05:40+08:00

app = "stupidjoey-gpt-reader"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:full"
  builtin = "python"
  [build.settings]
    pythonbase = "3.9-slim-buster"

[env]
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/data/myGPTReader"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
